export interface QaBacklogRow {
  area: string
  feature: string
  qaNeed: string
  neededApis: string
  status: string
}

export const QA_DASHBOARD_BACKLOG_ROWS: QaBacklogRow[] = [
  {
    area: 'CRM workflow',
    feature: 'Business lifecycle, cause lifecycle, readiness scoring, blockers, and next-action planning.',
    qaNeed: 'Lifecycle fields plus a workflow domain for steps, completion state, blockers, and readiness.',
    neededApis: 'GET/PUT lifecycle state, GET checklist, COMPLETE step, LIST blockers, LIST next actions.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'CRM activity',
    feature: 'Outreach log timeline for calls, emails, texts, visits, referrals, and follow-up outcomes.',
    qaNeed: 'Outreach activity table tied to business, cause, or stakeholder records.',
    neededApis: 'LIST outreach, CREATE outreach, UPDATE outreach, DELETE outreach.',
    status: 'Needs QA fields + APIs',
  },
  {
    area: 'CRM activity',
    feature: 'AI-supported outreach scripts and pushed script history tied back into CRM records.',
    qaNeed: 'Stored script drafts, outcomes, script metadata, and CRM linkage.',
    neededApis: 'LIST scripts, CREATE script log, UPDATE script outcome, LINK script to entity.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'CRM execution',
    feature: 'Tasks for businesses, causes, and team members with priority, due date, assignee, and completion.',
    qaNeed: 'Task table and assignment model in QA.',
    neededApis: 'LIST tasks, CREATE task, UPDATE task, COMPLETE task, ARCHIVE task.',
    status: 'Needs QA fields + APIs',
  },
  {
    area: 'CRM execution',
    feature: 'Notes attached to businesses, causes, and other dashboard records.',
    qaNeed: 'Notes table with author, timestamps, entity references, and internal/public flags.',
    neededApis: 'LIST notes, CREATE note, UPDATE note, DELETE note.',
    status: 'Needs QA fields + APIs',
  },
  {
    area: 'CRM contacts',
    feature: 'Contact records, invite state, joined state, and 100-list tracking inside the dashboard.',
    qaNeed: 'Contact/lead table plus contact status fields and list participation state.',
    neededApis: 'LIST contacts, CREATE contact, UPDATE contact, IMPORT join state, ARCHIVE contact.',
    status: 'Needs QA fields + APIs',
  },
  {
    area: 'CRM ownership',
    feature: 'Owner assignment, helper assignment, stakeholder roles, and local access relationships.',
    qaNeed: 'Assignment/relationship tables between accounts, users, and dashboard roles.',
    neededApis: 'LIST assignments, ASSIGN owner, ADD helper, REMOVE helper, LIST stakeholders.',
    status: 'Needs QA relationship model',
  },
  {
    area: 'Codes + links',
    feature: 'Referral codes, connection codes, and join URLs used by the material engine and capture flows.',
    qaNeed: 'Stakeholder code domain or equivalent QA fields tied to account records.',
    neededApis: 'GET codes, UPSERT codes, RESOLVE join URL, VALIDATE code uniqueness.',
    status: 'Needs QA fields + APIs',
  },
  {
    area: 'Branding',
    feature: 'Logo and cover-photo uploads used in listing previews, QR-linked assets, and generated materials.',
    qaNeed: 'Brand asset storage fields plus file upload endpoints in QA.',
    neededApis: 'UPLOAD logo, UPLOAD cover photo, GET brand assets, DELETE/REPLACE brand assets.',
    status: 'Needs QA file workflow',
  },
  {
    area: 'Offers',
    feature: 'Capture offer setup, cashback setup, launch-ready offer copy, and business-facing value props.',
    qaNeed: 'Offer configuration model for capture offers and dashboard-side launch offers.',
    neededApis: 'LIST offers, CREATE offer, UPDATE offer, ARCHIVE offer.',
    status: 'Needs QA offer domain',
  },
  {
    area: 'QR codes',
    feature: 'QR code generation, linking, collections, redirects, and QR analytics inside the dashboard.',
    qaNeed: 'QR code, collection, redirect, and scan-event domain in QA.',
    neededApis: 'LIST qr codes, CREATE qr code, UPDATE redirect, LIST collections, LIST scan analytics.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Materials',
    feature: 'Materials library, template assignment, library folders, and stakeholder material mapping.',
    qaNeed: 'Material library domain, template metadata, and entity assignment model in QA.',
    neededApis: 'LIST materials, CREATE material, UPDATE material, ASSIGN material, LIST templates.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Materials',
    feature: 'Generated materials, regeneration, version history, archive/restore, and generated file tracking.',
    qaNeed: 'Generated material records with versioning, storage pointers, generation status, and restore actions.',
    neededApis: 'GENERATE material, LIST generated versions, RESTORE version, ARCHIVE generated file.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Campaigns',
    feature: 'Campaign creation, campaign linking, and campaign-driven launch management.',
    qaNeed: 'Campaign table and campaign-to-account relationship model in QA.',
    neededApis: 'LIST campaigns, CREATE campaign, UPDATE campaign, LINK account to campaign.',
    status: 'Needs QA fields + APIs',
  },
  {
    area: 'Cities',
    feature: 'City records, city ownership, city views, and city access request handling.',
    qaNeed: 'City domain plus city access request tables in QA.',
    neededApis: 'LIST cities, CREATE city, UPDATE city, LIST access requests, RESOLVE access request.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Relations',
    feature: 'Business-to-cause linking and other dashboard-level relationship tracking.',
    qaNeed: 'Explicit account relationship model in QA beyond current account basics.',
    neededApis: 'LINK business to cause, UNLINK business from cause, LIST linked accounts.',
    status: 'Needs QA relationship model',
  },
  {
    area: 'Data quality',
    feature: 'Duplicate detection, duplicate review, archive-as-duplicate, and later merge workflows.',
    qaNeed: 'Duplicate flagging and merge-resolution domain in QA.',
    neededApis: 'LIST possible duplicates, FLAG duplicate, CLEAR duplicate, MERGE records, ARCHIVE duplicate.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Admin workflow',
    feature: 'Admin tasks, setup tasks, and material-engine operational queues.',
    qaNeed: 'Operational task tables and queue state in QA.',
    neededApis: 'LIST admin tasks, CREATE admin task, UPDATE admin task, COMPLETE admin task.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Analytics',
    feature: 'Dashboard analytics rollups, QR analytics, outreach analytics, and personal performance views.',
    qaNeed: 'Reporting/analytics endpoints or rollup tables in QA.',
    neededApis: 'GET dashboard metrics, GET outreach metrics, GET QR metrics, GET user performance.',
    status: 'Needs QA analytics domain',
  },
  {
    area: 'Business portal',
    feature: 'Portal setup progress, 100-list growth, business activity, and portal growth flows.',
    qaNeed: 'Portal-specific workflow fields and portal-facing operational APIs in QA.',
    neededApis: 'GET portal setup, UPDATE portal setup, LIST portal clients, GET business activity.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Community portal',
    feature: 'Community share links, supporter lists, mobilization activity, and community QR/material views.',
    qaNeed: 'Community engagement domain tied to causes and schools in QA.',
    neededApis: 'GET share stats, LIST supporters, GET community activity, LIST community QR assets.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Influencer / affiliate',
    feature: 'Influencer links, referral sharing, and personal referral statistics.',
    qaNeed: 'Influencer/affiliate link tracking and stats in QA.',
    neededApis: 'LIST influencer links, CREATE share link, GET referral stats.',
    status: 'Needs QA workflow domain',
  },
  {
    area: 'Admin / audit',
    feature: 'Audit log, material-engine administration, and dashboard-side operational settings.',
    qaNeed: 'Audit event model plus admin settings domain in QA.',
    neededApis: 'LIST audit events, LIST settings, UPDATE settings, LIST generation queue.',
    status: 'Needs QA admin domain',
  },
]
