server {
    listen 80;
    server_name dashboard-qa.5.252.52.243.sslip.io my-qa.5.252.52.243.sslip.io;
    location /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
    location / { return 404; }
}
